name: build

on:
  - push
  - pull_request

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
      env: { LANG: "C.UTF-8" }
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          apt-get update
          apt-get install -y build-essential git make pkg-config cmake ninja-build libasound2-dev libpulse-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev libwayland-dev ca-certificates wget zip --no-install-recommends

      - name: Build
        run: |
          ./build.sh

      - name: Archive
        run: |
          tar czf deps.tar.gz --directory=out/ ./

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deps-artifact
          path: deps.tar.gz

      - name: Upload and tag
        uses: pyTooling/Actions/releaser@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'latest'
          files: deps.tar.gz
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
